import GetGPTCode from "./services/GetGPTCode/GetGPTCode.js";
import GetChatGPTArt from "./services/GetChatGPTArt/GetChatGPTArt.js";
import TranslateObject from "./services/TranslateObject/TranslateObject.js";
import TranslateText from "./services/TranslateText/TranslateText.js";
import GetChatGPTFunction from "./services/GetChatGPTFunction/GetChatGPTFunction.js";
import CompileArduinoSketch from "./services/CompileArduinoSketch/CompileArduinoSketch.js";
import CreateArduinoSketch from "./services/CreateArduinoSketch/CreateArduinoSketch.js";
import UploadFileToCloud from "./services/UploadFileToCloud/UploadFileToCloud.js";
import DeleteFileFromCloud from "./services/DeleteFileFromCloud/DeleteFileFromCloud.js";
import TransformCloudFile from "./services/TransformCloudFile/TransformCloudFile.js";
import GetGPTOutput from "./services/GetGPTOutput/GetGPTOutput.js";
import GetWorkStatus from "./services/GetWorkStatus/GetWorkStatus.js";
import GetAPISubscriptionLink from "./services/GetAPISubscriptionLink/GetAPISubscriptionLink.js";
import Buy5KAPICreditsLink from "./services/Buy5KAPICreditsLink/Buy5KAPICreditsLink.js";
import GetAPIClientInfo from "./services/GetAPIClientInfo/GetAPIClientInfo.js";
import UpdateWorkData from "./services/UpdateWorkData/UpdateWorkData.js";
declare const _default: {
    GetGPTCode: typeof GetGPTCode;
    GetChatGPTArt: typeof GetChatGPTArt;
    TranslateObject: typeof TranslateObject;
    TranslateText: typeof TranslateText;
    GetChatGPTFunction: typeof GetChatGPTFunction;
    CompileArduinoSketch: typeof CompileArduinoSketch;
    CreateArduinoSketch: typeof CreateArduinoSketch;
    UploadFileToCloud: typeof UploadFileToCloud;
    DeleteFileFromCloud: typeof DeleteFileFromCloud;
    TransformCloudFile: typeof TransformCloudFile;
    GetGPTOutput: typeof GetGPTOutput;
    GetAPISubscriptionLink: typeof GetAPISubscriptionLink;
    Buy5KAPICreditsLink: typeof Buy5KAPICreditsLink;
    GetAPIClientInfo: typeof GetAPIClientInfo;
    GetWorkStatus: typeof GetWorkStatus;
    UpdateWorkData: typeof UpdateWorkData;
};
export default _default;
//# sourceMappingURL=index.d.ts.map